class Car {
  final String name;
  final String description;
  final String image;
  final String ownerphone;
  final String ownername;
  final double pricePerDay;
  final String category;
  final double rate;
  int quantity;

  Car(
      {required this.name,
      required this.ownerphone,
      required this.description,
      required this.image,
      required this.pricePerDay,
      required this.ownername,
      required this.category,
      required this.rate,
      required this.quantity});
}

List<Car> all() {
  return [
    Car(
      name: "Innova",
      description: "Petrol\n50L",
      image: "assets/images/innova.png",
      pricePerDay: 25,
      ownername: "Shane",
      category: "Mpv",
      ownerphone: "987655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "I-20",
      description: "Petrol\n 50L",
      image: "assets/images/i20.png",
      pricePerDay: 15,
      ownername: "George",
      category: "Hatchback",
      ownerphone: "987655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Nissan GTR",
      description: "Diesel\n70L",
      image: "assets/images/gtr.png",
      pricePerDay: 80,
      ownername: "Seban",
      category: "Sportscar",
      ownerphone: "987655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Audi R8",
      description: "Diesel\n70L",
      image: "assets/images/audi.png",
      pricePerDay: 80,
      ownername: "Hish",
      category: "Sportscar",
      ownerphone: "9856432112",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Benz GLE",
      description: "Diesel\n70L",
      image: "assets/images/benz_gle.png",
      pricePerDay: 80,
      ownername: "Roby",
      category: "Suv",
      ownerphone: "987655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Benz GLK",
      description: "Diesel\n70L",
      image: "assets/images/benz_glk.png",
      pricePerDay: 80,
      ownername: "Jacob",
      category: "Suv",
      ownerphone: "987655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Mustang",
      description: "Diesel\n70L",
      image: "assets/images/mustang.png",
      pricePerDay: 80,
      ownername: "Kane",
      category: "Pony car",
      ownerphone: "987655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Fortuner",
      description: "Diesel\n70L",
      image: "assets/images/fortuner1.png",
      pricePerDay: 80,
      ownername: "Williams",
      category: "Suv",
      ownerphone: "987655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Creta",
      description: "Diesel\n70L",
      image: "assets/images/creta.png",
      pricePerDay: 80,
      ownername: "Ramen",
      category: "Suv",
      ownerphone: "987655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Polo GT",
      description: "Diesel\n70L",
      image: "assets/images/polo gt.png",
      pricePerDay: 80,
      ownername: "Diana",
      category: "Hatchback",
      ownerphone: "987655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Ferrari",
      description: "Diesel\n70L",
      image: "assets/images/ferrari.png",
      pricePerDay: 80,
      ownername: "Lilli",
      category: "Sports car",
      ownerphone: "907455XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Endeavor",
      description: "Diesel\n70L",
      image: "assets/images/endeavor.png",
      pricePerDay: 80,
      ownername: "Weyn",
      category: "Suv",
      ownerphone: "907655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Porsche",
      description: "Diesel\n70L",
      image: "assets/images/porsche.png",
      pricePerDay: 80,
      ownername: "Rahul",
      category: "Sports car",
      ownerphone: "989655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Mini Cooper",
      description: "Diesel\n70L",
      image: "assets/images/mini cooper.png",
      pricePerDay: 80,
      ownername: "Shinto",
        category: "Hatchback",
      ownerphone: "987755XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Lexus",
      description: "Diesel\n70L",
      image: "assets/images/lexus1.png",
      pricePerDay: 80,
      ownername: "Felix",
      category: "Luxury",
      ownerphone: "987635XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "MG Hector",
      description: "Diesel\n70L",
      image: "assets/images/mg hector.png",
      pricePerDay: 80,
      ownername: "Leao",
      category: "Suv",
      ownerphone: "887455XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Thar",
      description: "Diesel\n70L",
      image: "assets/images/thar.png",
      pricePerDay: 80,
      ownername: "Lamine",
      category: "Suv",
      ownerphone: "987664XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Defender",
      description: "Diesel\n70L",
      image: "assets/images/defender.png",
      pricePerDay: 80,
      ownername: "Lashen",
      category: "Suv",
      ownerphone: "967655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Harrier",
      description: "Diesel\n70L",
      image: "assets/images/harrier.png",
      pricePerDay: 80,
      ownername: "Limbo",
      category: "Suv",
      ownerphone: "987655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
    Car(
      name: "Compass",
      description: "Diesel\n70L",
      image: "assets/images/jeep-compass.png",
      pricePerDay: 80,
      ownername: "Ayra",
      category: "Suv",
      ownerphone: "987655XXXX",
      rate: 4.8,
      quantity: 1,
    ),
  ];
}

final List<Car> suv = [
  Car(
    name: "Headphones",
    description: "Diesel\n70L",
    image: "assets/electronics/jbl.png",
    pricePerDay: 80,
    ownername: "JBL",
    category: "suv",
    ownerphone: "(320 Reviews)",
    rate: 4.8,
    quantity: 1,
  ),
];
final List<Car> sedan = [
  Car(
    name: "Headphones",
    description: "Diesel\n70L",
    image: "assets/electronics/jbl.png",
    pricePerDay: 80,
    ownername: "JBL",
    category: "sedan",
    ownerphone: "(320 Reviews)",
    rate: 4.8,
    quantity: 1,
  ),
];
